function Hd = train1BPfilt
%TRAIN1BPFILT Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
% Generated on: 12-Jul-2022 13:58:42

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 256.41;  % Sampling Frequency

Fstop1 = 0.1;             % First Stopband Frequency
Fpass1 = 0.6;             % First Passband Frequency
Fpass2 = 50.5;            % Second Passband Frequency
Fstop2 = 51.5;            % Second Stopband Frequency
Dstop1 = 0.001;           % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0001;          % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
